#!/usr/bin/env python3
"""
Get the correct API token format for Label Studio
"""

print("🔑 How to Get Your Label Studio API Token")
print("=" * 60)
print()
print("The token you provided appears to be a JWT refresh token,")
print("but we need an API access token.")
print()
print("📝 Steps to get the correct token:")
print()
print("1. Open Label Studio: http://localhost:8080")
print()
print("2. Log in if needed")
print()
print("3. Click on your username/avatar (top right corner)")
print()
print("4. Select 'Account & Settings'")
print()
print("5. Look for 'Access Token' section")
print()
print("6. Click 'Copy Token' or 'Generate Token' if not visible")
print()
print("7. The token should look like:")
print("   Format: Random alphanumeric string (40+ characters)")
print("   Example: d8f3b2a1c4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9")
print()
print("⚠️  The JWT token you provided starts with 'eyJ...'")
print("   This is NOT the right token format.")
print()
print("Once you have the correct token, run:")
print("   ./start_batch_predictions.sh")
print()
print("Or set it as environment variable:")
print("   export API_TOKEN='your-correct-token'")
print("   python3 generate_predictions_batch.py")
print()
print("=" * 60)
